# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: data-factory-validate
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
            # Directory that contains all Data Factory resources
            path: ./
            # Data Factory resource ID
            id: /subscriptions/cab35af7-0441-48ff-9577-8e6ec623c9e5/resourceGroups/AzurePolicyTest-RG/providers/Microsoft.DataFactory/factories/GithubEnterpriseTestADF-org

      - name: Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.1.0
        with:
          path: ./
          id: /subscriptions/cab35af7-0441-48ff-9577-8e6ec623c9e5/resourceGroups/AzurePolicyTest-RG/providers/Microsoft.DataFactory/factories/GithubEnterpriseTestADF-org

      - name: Publish ARM template
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: AzurePolicyTest-RG
          dataFactoryName: GithubEnterpriseTestADF-UAT
          armTemplateFile: ./armTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: ./armTemplate/ARMTemplateParametersForFactory.json
